include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    prefer_relative_imports: true
    public_member_api_docs: false
    sort_constructors_first: false
